### ISSUE TITLE
AttributeError: 'Munch' object has no attribute 'datasource' for datasource-breakdown

### ISSUE THREAD

**Issue by jangaraj** [panodata/grafana-wtf#17]
Thank you for the new `datasource-breakdown` feature. It seems to be a problem for my case (Grafana 6.1.x):
```
root@dee6c9aa6148:/# grafana-wtf --cache-ttl=1200 --concurrency=10 datasource-breakdown
2021-12-10 17:03:41,821 [grafana_wtf.core      ] INFO   : Setting up response cache to expire after 1200 seconds
2021-12-10 17:03:41,827 [grafana_wtf.core      ] INFO   : Scanning dashboards
2021-12-10 17:03:41,881 [grafana_wtf.core      ] INFO   : Found 2328 dashboards
  0%|                                                                                                                               | 0/2328 [00:00<?, ?it/s]2021-12-10 17:03:41,904 [grafana_wtf.core      ] INFO   : Fetching dashboards in parallel with 10 concurrent requests
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2328/2328 [00:36<00:00, 63.30it/s]
2021-12-10 17:04:18,678 [grafana_wtf.core      ] INFO   : Scanning datasources
2021-12-10 17:04:18,741 [grafana_wtf.core      ] INFO   : Found 422 data sources
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/munch/__init__.py", line 103, in __getattr__
    return object.__getattribute__(self, k)
AttributeError: 'Munch' object has no attribute 'datasource'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/munch/__init__.py", line 106, in __getattr__
    return self[k]
KeyError: 'datasource'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/grafana-wtf", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/grafana_wtf/commands.py", line 198, in run
    results = engine.datasource_breakdown()
  File "/usr/local/lib/python3.9/site-packages/grafana_wtf/core.py", line 293, in datasource_breakdown
    ix = Indexer(engine=self)
  File "/usr/local/lib/python3.9/site-packages/grafana_wtf/core.py", line 336, in __init__
    self.index()
  File "/usr/local/lib/python3.9/site-packages/grafana_wtf/core.py", line 339, in index
    self.index_dashboards()
  File "/usr/local/lib/python3.9/site-packages/grafana_wtf/core.py", line 360, in index_dashboards
    ds_panels = self.collect_datasource_names(dashboard.dashboard.panels)
  File "/usr/local/lib/python3.9/site-packages/grafana_wtf/core.py", line 344, in collect_datasource_names
    return list(set([item.datasource for item in root if item.datasource]))
  File "/usr/local/lib/python3.9/site-packages/grafana_wtf/core.py", line 344, in <listcomp>
    return list(set([item.datasource for item in root if item.datasource]))
  File "/usr/local/lib/python3.9/site-packages/munch/__init__.py", line 108, in __getattr__
    raise AttributeError(k)
AttributeError: datasource

root@dee6c9aa6148:/# pip list
Package            Version
------------------ ---------
appdirs            1.4.4
attrs              21.2.0
cattrs             1.9.0
certifi            2021.10.8
charset-normalizer 2.0.9
colored            1.4.3
decorator          5.1.0
docopt             0.6.2
grafana-api        1.0.3
grafana-wtf        0.11.0
idna               3.3
jsonpath-rw        1.4.0
munch              2.5.0
pip                21.0.1
ply                3.11
Pygments           2.10.0
PyYAML             5.4.1
requests           2.26.0
requests-cache     0.8.1
setuptools         53.0.0
six                1.16.0
tabulate           0.8.9
tqdm               4.62.3
url-normalize      1.4.3
urllib3            1.26.7
wheel              0.36.2
WARNING: You are using pip version 21.0.1; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```

**Comment by amotl** [comment]
Hi Jan,

thank you for reporting back so quickly about that new feature. Apparently, the accessor routines which decode the nested data structure of a Grafana dashboard are not graceful enough. I will look into it and publish a patch release after fixing the flaw.

With kind regards,
Andreas.

**Comment by amotl** [comment]
It looks like there is one or more dashboard(s) with panels, where those panels do not have a `datasource` attribute. That sounds reasonable, specifically when looking at HTML/JSON/iframe panel types, right?

```python
  File "/usr/local/lib/python3.9/site-packages/grafana_wtf/core.py", line 360, in index_dashboards
    ds_panels = self.collect_datasource_names(dashboard.dashboard.panels)
```

**Comment by amotl** [comment]
Dear Jan,

this has been improved with `grafana-wtf>=0.11.1`. Please let me know if you find any other issues.

With kind regards,
Andreas.

**Comment by jangaraj** [comment]
Thank you Andreas. It works like a charm now 👍. Yes, some panels may not have `datasource` property, e.g. row type.
